School_Management_System/Controllers/FacultyController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using School_Management_System.data;
using School_Management_System.Models;

namespace School_Management_System.Controllers
{
    public class FacultyController : Controller

    {
        private readonly schoolDbContext _context;
        public FacultyController(schoolDbContext context)
        {
            _context = context;
        }
        // GET: StudentController
        public async Task<IActionResult> Index()
        {
            var ft = await _context.FacultiesTable.ToListAsync();
            return View(ft);
        }

        // GET: StudentController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            if (id == null || _context.FacultiesTable == null)
            {
                return NotFound();
            }
            var ft = await _context.FacultiesTable.FirstOrDefaultAsync(fc => fc.Id == id);
            if (ft == null)
            {
                return NotFound();
            }
            return View(ft);
        }

        // GET: StudentController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: StudentController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(faculty ft)
        {
            try
            {
                _context.FacultiesTable.Add(ft);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(ft);
            }
            return View(ft);
        }

        // GET: StudentController/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null || _context.FacultiesTable == null)
            {
                return NotFound();

            }
            var ft = await _context.FacultiesTable.FindAsync(id);
            if (ft == null)
            {
                return NotFound();
            }
            return View(ft);
        }

        // POST: StudentController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, faculty ft)
        {
            if (id != ft.Id)
            {
                return NotFound();

            }
            _context.FacultiesTable.Update(ft);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));


        }


        // GET: StudentController/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null || _context.FacultiesTable == null)
            {
                return NotFound();

            }
            var stu = await _context.FacultiesTable.FirstOrDefaultAsync(ft => ft.Id == id);
            if (stu == null)
            {
                return NotFound();
            }
            return View(stu);
        }

        // POST: StudentController/Delete/5
        [HttpPost,ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id, faculty ft)
        {
            var existing = await _context.FacultiesTable.FirstOrDefaultAsync(fc => fc.Id == id);
            if (existing == null)
            {
                throw new ArgumentException($"Employee Does not exists");
            }
            _context.Entry(existing).State = EntityState.Deleted;
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

School_Management_System/Controllers/StudentController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using School_Management_System.data;
using School_Management_System.Models;

namespace School_Management_System.Controllers
{
    public class StudentController : Controller

    {
        private readonly schoolDbContext _context;
        public StudentController(schoolDbContext context)
        {
            _context = context;
        }
        // GET: StudentController
        public async Task<IActionResult> Index()
        {
            var st = await _context.StudentTable.ToListAsync();
            return View(st);
        }

        // GET: StudentController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            if (id == null || _context.StudentTable == null)
            {
                return NotFound();
            }
            var stu = await _context.StudentTable.FirstOrDefaultAsync(st => st.Id == id);
            if (stu == null)
            {
                return NotFound();
            }
            return View(stu);
        }

        // GET: StudentController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: StudentController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(student stu)
        {
            try
            {
                _context.StudentTable.Add(stu);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(stu);
            }
            return View(stu);
        }

        // GET: StudentController/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null || _context.StudentTable == null)
            {
                return NotFound();

            }
            var stu = await _context.StudentTable.FindAsync(id);
            if (stu == null)
            {
                return NotFound();
            }
            return View(stu);
        }

        // POST: StudentController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, student stu)
        {
            if (id != stu.Id)
            {
                return NotFound();

            }
            _context.StudentTable.Update(stu);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));


        }


        // GET: StudentController/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null || _context.StudentTable == null)
            {
                return NotFound();

            }
            var stu = await _context.StudentTable.FirstOrDefaultAsync(st => st.Id == id);
            if (stu == null)
            {
                return NotFound();
            }
            return View(stu);
        }

        // POST: StudentController/Delete/5
        [HttpPost,ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id, student stu)
        {
            var existing = await _context.StudentTable.FirstOrDefaultAsync(st => st.Id == id);
            if (existing == null)
            {
                throw new ArgumentException($"Student Does not exists");
            }
            _context.Entry(existing).State = EntityState.Deleted;
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

    }
}

School_Management_System/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - School_Management_System</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/School_Management_System.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">School_Management_System</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Student</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Faculty" asp-action="Index">Faculty</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - School_Management_System - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>